# Generated by Django 2.0.13 on 2019-07-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_portrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('match_name', models.TextField()),
                ('poem', models.TextField()),
                ('children', models.TextField()),
            ],
        ),
    ]
